disabled_rules:
  - redundant_string_enum_value
  - line_length
  - trailing_whitespace
  - identifier_name

opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - operator_usage_whitespace

  - array_init
  - contains_over_first_not_nil
  - joined_default_parameter
  - line_length
  - literal_expression_end_indentation
  - multiline_parameters
  - override_in_extension
  - pattern_matching_keywords
  - redundant_string_enum_value
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

  - nimble_operator
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - single_test_class

  # - closure_end_indentation
  # - let_var_whitespace
  # - implicitly_unwrapped_optional
  # - private_outlet
  # - object_literal
  # - sorted_imports
  # - strict_fileprivate
  # - switch_case_on_newline

#included:

#excluded:

cyclomatic_complexity:
  warning: 25

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 800

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - Id
    - Ad

nesting:
  type_level:
    warning: 3
    error: 5

superfluous_disable_command: warning
force_unwrapping: error
trailing_semicolon: error

reporter: "xcode"

custom_rules:
  new_line_after_method_signature:
    include: "*.swift"
    name: "New line after method signature"
    regex: '\{\n\s*\n+\s*\w'
    message: "No new line after curly braces and before code"
    severity: warning
  new_line_between_braces:
    include: "*.swift"
    name: "New line after }"
    regex: '\}\n\s*\n+\s*\}'
    message: "No new line between curly braces"
    severity: warning
